---
- name: Copy velox rsyslog configuration file
  template: 
    src: ../templates/99-velox.conf
    dest: /etc/rsyslog.d/99-velox.conf
    mode: 0644
  notify:
    - Reload Rsyslog

- name: Create directories
  file:
    path: "{{ scratch }}/{{ item }}"
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: 0744
  with_items:
    - ''
    - storage
    - hadoop/storage
    - hadoop/name

- name: Create ldconfig file
  template:
    src: ../templates/boost-ld.conf
    dest: /etc/ld.so.conf.d/boost-ld.conf
    mode: 0644

- name: Reload ldconfig cache
  command: ldconfig
