---
- hosts: veloxmaster
  become: true
  roles:
    - master

- hosts: veloxservers
  become: true
  roles:
    - common
    - slaves

- hosts: zkserver 
  become: true
  roles:
    - common
    - zkmaster 
