---
- hosts: all
  become: true
  vars:
    boost_version: '1.59.0'
    boost_prefix: '/usr/local'
  roles:
    - kawasakitoshiya.boost-install
  tags:
    - boost

# install zookeeper in shared directory
- hosts: master
  vars:
    prefix: '~/sandbox'
    build_dir: '~/opt' 
  roles:
    - vicentebolea.zookeeper_c_lib
    - velox-hadoop-configuration
    
- hosts: master
  become: true
  roles:
    - master

- hosts: slaves
  become: true
  roles:
    - common
    - slaves

- hosts: zkserver 
  become: true
  roles:
    - zkmaster 
  tags:
    - zk

