---
- name: Install needed packages
  apt: pkg={{ item }} state=installed
  with_items: 
  - automake
  - build-essential
  - libtool
  - sysstat
  - gdb
  - libboost-all-dev
  - libsqlite3-dev
  - libsqlite3-0
  when: ansible_distribution == "Ubuntu"

- name: Install needed packages
  yum: pkg={{ item }} state=installed
  with_items: 
  - gdb
  - sysstat
  - maven
  when: ansible_distribution == "CentOS"

- name: Enable core dump
  lineinfile:
    path: /etc/security/limits.conf
    state: present
    line: '* soft core unlimited'
  when: ansible_distribution == "CentOS"
