---

- name: Create log folder
  file: 
    path: /var/log/velox
    state: directory
    mode: 0755

- name: Copy velox rsyslog config file
  copy: 
    src: ../files/99-velox-master.conf
    dest: /etc/rsyslog.d/99-velox.conf
    mode: 0644

  notify:
    - Reload logrotate
    - Reload Rsyslog

- name: Copy velox logrotate config file
  copy: 
    src: ../files/velox-logrotate
    dest: /etc/logrotate.d/velox-logrotate
    mode: 0644

  notify:
    - Reload logrotate
    - Reload Rsyslog

- name: Install needed packages
  yum: pkg={{ item }} state=installed
  with_items: 
  - automake
  - autoconf
  - libtool
  - libsqlite3x-devel
  when: ansible_distribution == "CentOS"
