---
- handlers:
    - name: Reload Rsyslog
      service: name=rsyslog state=started

    - name: Reload logrotate
      service: name=logrotate state=started

- hosts: lynxmaster
  remote_user: root
  tasks: 
  - name: Create log directory 
    file: path=/var/log/velox state=directory mode=0766 owner=syslog group=syslog
    notify: Setup logs

  - name: Rsyslog master configuration file
    file: 
      src: 99-velox-master.conf
      dest: /etc/rsyslog.d/99-velox.conf
      mode: 0774
    listen: Setup logs

  - name: LogRotate setup files
    file: 
      src: velox-logrotate
      dest: /etc/logrotate.d/velox-logrotate
      mode: 0774
    listen: Setup logs

    notify:
      - Reload logrotate
      - Reload Rsyslog

- hosts: lynx01 lynx02
  remote_user: root
  vars:
    resource_manager: 'lynxmaster'
  tasks:
   - name: Rsyslog remote nodes configuration file
     template: 
       src: 99-velox.conf
       dest: /etc/rsyslog.d/99-velox.conf
       mode: 0774
     notify:
       - Reload Rsyslog

